// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
  }
}
